\LoadClass[11pt,a4paper,sans]{moderncv} 
% a4, a5, b5, legalpaper, executivepaper, landscape

% moderncv themes
\moderncvstyle{banking} % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
\moderncvcolor{red}% color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'


% personal data
\name{Mohamed Iheb}{Faiza}
\title{Engineering Student} % optional, remove / comment the line if not wanted
\address{SAINT-ELOI}{Montpellier, France}% optional, 
\phone[mobile]{+33777002237} % optional, remove / comment the line if not wanted
\email{fmohamediheb@gmail.com} % optional, remove / comment the line if not wanted
\homepage{medihebfaiza.com} % optional, remove / comment the line if not wanted
\social[github][github.com/medihebfaiza]{medihebfaiza}
%\social[linkedin][linkedin.com/in/username]{username} 
%can also do twitter

%\renewcommand{\familydefault}{\sfdefault} % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
%\nopagenumbers{} % uncomment to suppress automatic page numbering for CVs longer than one page

% character encoding
\RequirePackage[utf8]{inputenc}

\RequirePackage{geometry} % changes margins across the page
\geometry{
left=15mm,
right=15mm,
top=40mm,
bottom=5mm,
}