\LoadClass[11pt,a4paper,sans]{moderncv} 
% a4, a5, b5, legalpaper, executivepaper, landscape

% moderncv themes
\moderncvstyle{banking} % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
\moderncvcolor{blue}% color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'


% personal data
\name{Mohamed Iheb}{FAIZA}
\title{Engineering Student} % optional, remove / comment the line if not wanted
\address{570 Route de Ganges}{Montpellier, France}% optional, 
\phone[mobile]{+33777002237} % optional, remove / comment the line if not wanted
\email{fmohamediheb@gmail.com} % optional, remove / comment the line if not wanted
\homepage{medihebfaiza.com} % optional, remove / comment the line if not wanted
\social[github][github.com/medihebfaiza]{medihebfaiza}
\social[linkedin][www.linkedin.com/in/medihebfaiza]{medihebfaiza} 
%can also do twitter
%\extrainfo{additional information}                 % optional, remove / comment the line if not wanted
%\photo[64pt][0.4pt]{photo}                       % optional, remove / comment the line if not wanted; '64pt' is the height the picture must be resized to, 0.4pt is the thickness of the frame around it (put it to 0pt for no frame) and 'picture' is the name of the picture file
%\quote{i get thing done !}
%\renewcommand{\familydefault}{\sfdefault} % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
%\nopagenumbers{} % uncomment to suppress automatic page numbering for CVs longer than one page

% character encoding
\RequirePackage[utf8]{inputenc}

\RequirePackage{geometry} % changes margins across the page
\geometry{
left=15mm,
right=15mm,
top=25mm,
bottom=5mm,
}